version: '3.1'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      API_URL : 'http://backend:8000/api/blog'
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: 'mongodb://mongo:27017/blogs'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
