version: '3.1'

services:
  backend:
    container_name: backend
    image: backend
    build:
      dockerfile: backend.dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: 'mongodb://mongo:27017/blogs'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
